### ISSUE TITLE
Error while launching TrackMate after update to v8

### ISSUE THREAD

**Issue by amichaut** [trackmate-sc/TrackMate#330]
I can't launch Trackmate since the update to the last version. See error below: 

`(Fiji Is Just) ImageJ 2.16.0/1.54p; Java 1.8.0_202 [64-bit]; Mac OS X 10.16; 285MB of 15810MB (1%)
 
java.lang.NoClassDefFoundError: fiji/plugin/trackmate/util/cli/ConfigGuiBuilder$ConfigPanel
	at fiji.plugin.trackmate.action.InTRACKtiveAction$Factory.getIcon(InTRACKtiveAction.java:84)
	at fiji.plugin.trackmate.gui.components.ModuleChooserPanel$MyListCellRenderer.getListCellRendererComponent(ModuleChooserPanel.java:131)
	at com.formdev.flatlaf.ui.FlatComboBoxUI$FlatComboPopup$PopupListCellRenderer.getListCellRendererComponent(FlatComboBoxUI.java:1048)
	at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
	at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
	at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2623)
	at com.formdev.flatlaf.ui.FlatListUI.lambda$createListSelectionListener$2(FlatListUI.java:196)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2216)
	at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1186)
	at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:65)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:1015)
	at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
	at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
	at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at fiji.plugin.trackmate.gui.components.ModuleChooserPanel.<init>(ModuleChooserPanel.java:102)
	at fiji.plugin.trackmate.gui.components.ActionChooserPanel.<init>(ActionChooserPanel.java:54)
	at fiji.plugin.trackmate.gui.wizard.descriptors.ActionChooserDescriptor.<init>(ActionChooserDescriptor.java:39)
	at fiji.plugin.trackmate.gui.wizard.TrackMateWizardSequence.<init>(TrackMateWizardSequence.java:151)
	at fiji.plugin.trackmate.TrackMatePlugIn.createSequence(TrackMatePlugIn.java:118)
	at fiji.plugin.trackmate.TrackMatePlugIn.run(TrackMatePlugIn.java:99)
	at fiji.plugin.trackmate.TrackMateRunner.run(TrackMateRunner.java:529)
	at ij.IJ.runUserPlugIn(IJ.java:244)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: fiji.plugin.trackmate.util.cli.ConfigGuiBuilder$ConfigPanel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
`
